<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;1,400&display=swap');
$this->headLink()->prependStylesheet('//use.typekit.net/hey6xcy.css');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }
            
            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header>
            <a class="unmc-link" href="https://unmc.libwizard.com/f/whctour" target="_blank" >Request a guided tour</a>
            <h1>
                <a href="https://www.unmc.edu/library/" class="site-title" target="_blank">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
           <!-- <div id="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>-->

            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
            
            <a id="mobile-menu-button" class="mobile" href="#mobile-nav"><span></span></a>
        </header>
        <div id="content" role="main">
           
            
            
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div id="footer-top">
                
                <div class="left">
                    
                    <a id="footer-logo" href="https://www.unmc.edu/" target="_blank">
                        <img src="https://exhibits.unmc.edu/themes/wigton/asset/img/unmc-logo-rev.svg" alt="UNMC">

                    </a>
                    
                    <?php if ($footerContent = $this->themeSetting('footer')): ?>
                    <?php echo $footerContent; ?>
                    <?php else: ?>
                        <?php echo $this->translate('Powered by Omeka S'); ?>
                    <?php endif; ?>
                </div>
                
                <div class="right">
                    <ul class="simple-list social-media">
                        
                        <li>
                            <a href="https://twitter.com/UNMCWigton" target="_blank">
                                <img src="https://exhibits.unmc.edu/themes/wigton/asset/img/twitter-rev.svg" alt="twitter">
                            </a>
                        </li>
                        
                    </ul>
                </div>
                
            </div>
            
            <div id="footer-bottom">
                
                <div class="left">
                    © University of Nebraska Medical Center
                </div>
                
                <div class="right">
                    
                    <ul id="footer-nav" class="simple-list">
                        
                        <li>
                            <a href="mailto:history@unmc.edu" target="_blank">Contact</a>
                        </li>
                        
                        <li>
                            <a href="https://unmc.libwizard.com/f/whctour" target="_blank">Request a Guided Tour</a>
                        </li>
                        
                        <li>
                            <a href="https://www.unmc.edu/wigton/" target="_blank">Wigton Heritage Center</a>
                        </li>
                        
                    </ul>
                    
                </div>
                
            </div>
            
        </footer>
    </body>
</html>
